
title: My Resume
url: 'https://aruizcastro.github.io'
baseurl: '/aruizcastro.github.io' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Aland Ruiz
tagline: Full Stack Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: hola@alandruiz.com
#phone: 012 345 6789
website: aruizcastro.github.io #do not add http://
linkedin: alandruizc
github: aruizcastro
#twitter: '@AlandRuizC'

#Update all the sections by editing the files inside _includes folder.
